schemes:
  theme:
    type: ReadOnlyStream
    prefixes:
      '':
      - wp-content/themes/nucleus
      - wp-content/themes/gantry

      css/:
      - wp-content/themes/nucleus/css-compiled
      - wp-content/themes/nucleus/css
      - wp-content/themes/gantry/css-compiled
      - wp-content/themes/gantry/css
