header:
  container:
    - particle-logo

navigation:
  container:
    - particle-menu

main:
  container:
    - position-breadcrumbs
    - position-global_messages
    - pagecontent

footer:
  container:
  - position-footer
  - [particle-copyright 40, spacer 30, particle-branding 30]
