schemes:
  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - templates/gantry
        - templates/gantry/common

      css/:
        - templates/gantry/css-compiled
        - templates/gantry/css
        - templates/gantry/common/css-compiled
        - templates/gantry/common/css
