schemes:
  themes:
    type: ReadOnlyStream
    prefixes:
      '':
      - templates

  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - themes://gantry
        - themes://gantry/common
