branding:
  css:
    classname: 'particle_gantry_branding'

copyright:
  date:
    start: 2007
    end: now
  owner: 'RocketTheme, LLC'

loginbutton:
  title:
  logintext: Login
  logouttext: Logout
  css:
    classname: 'particle_gantry_loginbutton'

logo:
  image: 'images/logo.png'
  text: 'Gantry'

menu:
  items:
    menu: ''
    base: 0
    startLevel: 1
    endLevel: 0
    showAllChildren: true
    window_open: 'width=200,height=300'
  css:
    id:
    class: 'main-nav'

totop:
  css:
    classname: 'particle_gantry_totop'
