schemes:
  designs:
    type: ReadOnlyStream
    paths:
      - app/design/frontend

  skins:
    type: ReadOnlyStream
    paths:
      - skin/frontend

  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - designs://gantry/default/gantry
        - designs://gantry/default/gantry/common

      css/:
        - skins://gantry/default/css-compiled
        - skins://gantry/default/css
        - skins://gantry/default/common/css-compiled
        - skins://gantry/default/common/css

      fonts/:
        - skins://gantry/default/fonts
        - skins://gantry/default/common/fonts

      images/:
        - skins://gantry/default/images
        - skins://gantry/default/common/images

      js/:
        - skins://gantry/default/js
        - skins://gantry/default/common/js
