schemes:
  gantry.theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - user/themes/afterburner2
        - user/themes/nucleus

      css/:
        - user/themes/afterburner2/css-compiled
        - user/themes/afterburner2/css
        - user/themes/nucleus/css-compiled
        - user/themes/nucleus/css

      js/:
        - user/themes/afterburner2/js
        - user/themes/nucleus/js

      fonts/:
        - user/themes/afterburner2/fonts
        - user/themes/nucleus/fonts

      images/:
        - user/themes/afterburner2/images
        - user/themes/nucleus/images
