services:
    template:
        class: rockettheme\gantry\template\twig\twig
        arguments:
            - @path_helper
            - @config
            - @user
            - @template_context
            - @ext.manager
    rockettheme.rokbb.listener:
        class: rockettheme\gantry\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
