schemes:
  theme:
    type: ReadOnlyStream
    prefixes:
      '':
      - wp-content/themes/gantry
      - wp-content/themes/gantry/common

      css/:
      - wp-content/themes/gantry/css-compiled
      - wp-content/themes/gantry/css
      - wp-content/themes/gantry/common/css-compiled
      - wp-content/themes/gantry/common/css
