schemes:
  themes:
    type: ReadOnlyStream
    prefixes:
      '':
        - wp-content/themes

  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - themes://gantry
        - themes://gantry/common
