branding:
  css:
    classname: 'widget_gantry_branding'

copyright:
  date:
    start: 2007
    end: now
  owner: 'RocketTheme, LLC'

login:
  title:
  logintext: Login
  logouttext: Logout
  css:
    classname: 'widget_gantry_login'

popup:
  text: Popup
  css:
    classname: 'widget_gantry_popup'

logo:
  image: 'images/logo.png'
  text: 'Gantry'

totop:
  css:
    classname: 'widget_gantry_totop'
