title: Main Menu
base: /

ordering:
  home:
  about:
  team:
  features:
    typography:
  sample-pages:
    - about-us:
        layout-1:
        layout-2:
        layout-3:
      our-team:
        layout-1:
        layout-2:
        layout-3:
      pricing:
        layout-1:
        layout-2:
        layout-3:
    - faq:
        layout-1:
        layout-2:
        layout-3:
      services:
        layout-1:
        layout-2:
        layout-3:
      blog:
        layout-1:
        layout-2:
        layout-3:
  special:
    - title:
      error:
      unsupported:
      offline:
    - comingsoon:
      separator:
      component:
      raw:
  admin:

items:
  home:
    menu_icon: fa fa-fw fa-home

  about:
    menu_icon: fa fa-fw fa-check

  team:
    menu_icon: fa fa-fw fa-users

  features:
    type: alias
    link: features/typography
    title: Features
    browserNav: 0
    params:
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: fa fa-fw fa-bolt

  sample-pages:
    type: separator
    title: Sample Pages
    menu_icon: fa fa-fw fa-fire
    layout: columns

  sample-pages/about-us:
    type: separator
    title: About Us
    menu_icon: fa fa-fw fa-ra

  sample-pages/our-team:
    type: separator
    title: Our Team
    menu_icon: fa fa-fw fa-users

  sample-pages/pricing:
    type: separator
    title: Pricing
    menu_icon: fa fa-fw fa-usd

  sample-pages/faq:
    type: separator
    title: FAQ
    menu_icon: fa fa-fw fa-book

  sample-pages/services:
    type: separator
    title: Services
    menu_icon: fa fa-fw fa-taxi

  sample-pages/blog:
    type: separator
    title: Blog
    menu_icon: fa fa-fw fa-calendar-o

  special:
    type: alias
    link: special/error
    title: Special Pages
    browserNav: 0
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: fa fa-fw fa-shield
    layout: columns

  special/title:
    type: heading
    title: Special Pages

  special/error:
    menu_icon: fa fa-fw fa-warning

  special/unsupported:
    menu_icon: fa fa-fw fa-wheelchair

  special/offline:
    menu_icon: fa fa-fw fa-power-off

  special/comingsoon:
    menu_icon: fa fa-fw fa-paint-brush

  special/separator:
    type: separator
    title: Component Stuff

  special/component:
    menu_icon: fa fa-fw fa-file-text-o

  special/raw:
    menu_icon: fa fa-fw fa-file-code-o

  admin:
    type: alias
    menu_icon: fa fa-fw fa-cogs
    link: admin
    title: Admin

  admin/overview:
    type: alias
    menu_icon: fa fa-fw fa-adjust
    link: admin
    title: Overview

  admin/presets:
    type: alias
    menu_icon: fa fa-fw fa-star
    link: admin/presets
    title: Presets

  admin/settings:
    type: alias
    menu_icon: fa fa-fw fa-wrench
    link: admin/settings
    title: Settings

  admin/pages:
    type: alias
    menu_icon: fa fa-fw fa-columns
    link: admin/pages
    title: Layouts

  admin/menu:
    type: alias
    menu_icon: fa fa-fw fa-list
    link: admin/menu
    title: Menu

  admin/assignments:
    type: alias
    menu_icon: fa fa-fw fa-check
    link: admin/assignments
    title: Assignments

  admin/themes:
    type: alias
    menu_icon: fa fa-fw fa-tint
    link: ../
    title: Back to Themes

  admin/learn:
    type: alias
    menu_icon: fa fa-fw fa-book
    link: ../learn
    title: Documentation
