settings:
  title: Main Menu
  base: /

ordering:
  home:
  admin:
    about:
    configurations:
    menu:
    themes:
    learn:

items:
  home:
    icon: fa fa-fw fa-home

  features:
    type: alias
    link: features/typography
    title: Features
    icon: fa fa-fw fa-bolt
    layout: columns

  sample-pages:
    title: Sample Pages
    icon: fa fa-fw fa-fire

  admin:
    type: separator
    title: Admin
    icon: fa fa-fw fa-cogs
    target: _blank

  admin/about:
    type: alias
    link: admin
    title: Theme Admin
    icon: fa fa-fw fa-question-circle
    target: _blank

  admin/configurations:
    type: alias
    link: admin/configurations
    title: Configurations
    icon: fa fa-fw fa-star
    target: _blank

  admin/menu:
    type: alias
    link: admin/menu
    title: Menu Manager
    icon: fa fa-fw fa-wrench
    target: _blank

  admin/themes:
    type: alias
    link: ../
    title: Back to Themes
    icon: fa fa-fw fa-tint
    target: _blank

  admin/learn:
    type: alias
    link: ../learn
    title: Documentation
    icon: fa fa-fw fa-tint
    target: _blank

  admin/download:
    type: alias
    link: ../builds/gantry5
    title: Download
    icon: fa fa-fw fa-book
    target: _blank
