enabled: true

css:
  id:
  class: 'social-items'

items:

  - icon: fa fa-twitter
    text: Twitter
    link: http://twitter.com/rockettheme

  - icon: fa fa-facebook
    text: Facebook
    link: http://facebook.com/rockettheme

  - icon: fa fa-google
    text: Google
    link: http://plus.google.com/+rockettheme

  - icon: fa fa-rss
    text: RSS
    link: http://www.rockettheme.com/product-updates?rss
