schemes:
  themes:
    type: ReadOnlyStream
    prefixes:
      '':
      - templates

  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - themes://afterburner2
        - themes://afterburner2/common
        - themes://gantry
        - themes://gantry/common

      css/:
        - themes://afterburner2/css-compiled
        - themes://afterburner2/css
        - themes://afterburner2/common/css-compiled
        - themes://afterburner2/common/css
        - themes://gantry/css-compiled
        - themes://gantry/css
        - themes://gantry/common/css-compiled
        - themes://gantry/common/css
