schemes:
  gantry-admin:
    type: ReadOnlyStream
    prefixes:
      '':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common

      'assets/':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common
