schemes:
  gantry-admin:
    type: ReadOnlyStream
    prefixes:
      '':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common
        - templates/nucleus

      'assets':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common
        - templates/nucleus
        - templates/nucleus/common
