config:
  menu: ''
  base: 0
  startLevel: 1
  endLevel: 0
  showAllChildren: true
  window_open: 'width=200,height=300'
css:
  id:
  class: 'main-nav'

ordering:
  home:
  about:
  features:
    typography:
  special:
    title:
    error:
    unsupported:
    offline:
    comingsoon:
    separator:
    component:
    raw:
  admin:
    themes:

items:
  features:
    type: alias
    link: features/typography
    title: Features
    browserNav: 0
    params:
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: lock

  special:
    type: alias
    link: special/error
    title: Special Pages
    browserNav: 0
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: lock

  special/title:
    type: heading
    title: Special Pages

  special/separator:
    type: separator
    title: Component Stuff

  admin:
    type: alias
    link: admin
    title: Admin

  admin/themes:
    type: alias
    link: ../
    title: Back to Themes
