schemes:
  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - templates/nucleus
        - templates/gantry

      css/:
        - templates/nucleus/css-compiled
        - templates/nucleus/css
        - templates/gantry/css-compiled
        - templates/gantry/css
